package com.example.accessingdatamysql;


import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class ProductoController {
  @Autowired // This means to get the bean called userRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  
  private ProductoRepository productoRepository;


  @PostMapping(path="/producto/add") // Map ONLY POST Requests
  public @ResponseBody String addNewProducto (@RequestParam String nombre
      , @RequestParam Double precio
      , @RequestParam Integer stock) {
    // @ResponseBody means the returned String is the response, not a view name
    // @RequestParam means it is a parameter from the GET or POST request

    Producto n = new Producto();
    n.setNombre(nombre);
    n.setPrecio(precio);
    n.setStock(stock);
    productoRepository.save(n);
    return "Saved";
  }

  @GetMapping(path="/producto/all")
  public @ResponseBody Iterable<Producto> getAllProducto() {
    // This returns a JSON or XML with the users
    return productoRepository.findAll();
  }
}
